### ISSUE TITLE
Engine itself should be free of Camera and Player.

### ISSUE THREAD

**Issue by bonesoul** [bonesoul/voxeliq#46]
As of right now, these exist in the Engine code itself but it should be free of them and Camera related the values should be provided by the game itself as configuration to Engine. So that anyone could just use it for FPS, RTS or some other kind of game.

Camera issues;
- [ ] https://github.com/Delwin9999/voxeliq/issues/16 - vertical looking is not clamped to prevent looking past vertical
- [ ] https://github.com/Delwin9999/voxeliq/issues/1 - Detachable camera
- [ ] https://github.com/Delwin9999/voxeliq/issues/2 - Move hard coded values out to asset files
- [ ] https://github.com/Delwin9999/voxeliq/issues/8 - Collision detection is off

Player issues;
- [ ] https://github.com/Delwin9999/voxeliq/issues/4 - Find aimed block is not finding the most intuitive choice for a block.
- [ ] https://github.com/raistlinthewiz/voxeliq/issues/72 - Block picking is offset

**Comment by Delwin9999** [comment]
There's the question of what is 'game' code and what is 'engine' code.  Maybe there should be three layers?  'Engine' 'Genre' and 'Game'?  It seems that things like a good first person controller or a good isometric camera would be very useful to have in a generic place that multiple games could pull from but likewise aren't really part of the engine per se.

**Comment by bonesoul** [comment]
Actually I was also thinking about this and had an idea like;
- SampleGames/ folder with samples for common genres
- A SampleGames/Common folder that can host those common stuff for genres

Yet, your idea is also quite viable, having the Engine itself, Samples/ folder and Utility/ library with common genre functionality provided.
