### ISSUE TITLE
Fix the engine architecture

### ISSUE THREAD

**Issue by bonesoul** [bonesoul/voxeliq#50]
We have major issues in engine architecture. 
- [ ] https://github.com/Delwin9999/voxeliq/issues/3 - Entire architecture is tightly coupled. Decouple it
- [ ] https://github.com/raistlinthewiz/voxeliq/issues/46 - Engine itself should be free of Camera and Player.
- [x] #43 - Engine is a singleton without the protections thereof.

**Comment by bonesoul** [comment]
I'm exploring the available options; I guess we can give a try to ninject based solution as in; 
- http://blog.nuclex-games.com/tutorials/xna/components-and-services/
- http://blog.nuclex-games.com/2010/08/to-gamecomponent-or-not-to-gamecomponent/
- http://steveproxna.blogspot.com/2011/03/xna-and-ioc-container.html
- http://steveproxna01di.codeplex.com/
- http://blog.nuclex-games.com/tutorials/dependency-injection/
- http://www.nuclex.org/articles/architecture/9-using-dependency-injection-in-xna

**Comment by Delwin9999** [comment]
OK this isn't the way I did dependency injection before but the existence of Ninject makes a lot of things easier.  I'll toy with it to see if I can get it working.

**Comment by bonesoul** [comment]
Yea and we really don't need to rush for this, better we go for functionality and stability at the first place and then we can go for architectural fixes.
